///AppName
String appname = 'Quizz';
String unknown = 'Unknown';

List<String> courses = [
  "Others...",
  "Clinical Pharmacy and Pharmacy Management",
  "Pharmaceutical Microbiology and Biotechnology",
  "Pharmaceutical Technology & Industrial Pharmacy",
  "Pharmaceutics",
  "Pharmacognosy and Environmental Medicines",
  "Pharmacology & THerapeutics",
  "Agric./Bioresources Engineering",
  "Civil Engineering",
  "Mechanical Engineering",
  "Electronic Engineering",
  "Metallurgical/Material Engineering",
  "Electrical Engineering",
  "Agricultural Economics",
  "Agricultural Extension",
  "Animal Science",
  "Crop Science",
  "Food Science and Technology",
  "Soil science",
  "Mass Communication",
  "Combined Arts",
  "Linguistics",
  "English & Literary Studies",
  "Creative Arts",
  "Fine and Applied Arts",
  "French",
  "French/German/Russia",
  "German",
  "History and International Studies",
  "Igbo",
  "Linguistics/Igbo/Other",
  "Nigerian Languages",
  "Archaeology",
  "Theatre and Film Studies",
  "Music",
  "Biochemistry",
  "Microbiology",
  "Botany",
  "Zoology",
  "Combined Biological Sciences",
  "Education Physics",
  "Education Biology",
  "Education Chemistry",
  "Education Geography",
  "Education Integrated Science",
  "Education Mathematics",
  "Education Science",
  "Computer Education",
  "Industrial Technical Education",
  "Early Childhood Education",
  "Education Music",
  "Education French",
  "Education History",
  "Education Igbo",
  "Education Arts",
  "Primary Education",
  "Special Education",
  "Education Economics",
  "Education Fine/Applied Arts",
  "Education Social Science",
  "Education Political Science",
  "Education Social Studies",
  "Guidance and Counselling",
  "Health Education",
  "Library and Information Science",
  "Physical Education",
  "Home Economics Education",
  "Agricultural Education",
  "Business Education",
  "Technical Industrial Education",
  "Pure/Industrial Chemistry",
  "Science Laboratory",
  "Geology",
  "Physics",
  "Statistics",
  "Computer/Statistics",
  "Veterinary Medicine",
  "Veterinary Anatomy",
  "Veterinary Obstetrics & Reproductive Diseases",
  "Veterinary Parasitology & Entomology",
  "Veterinary Pathology & Microbiology",
  "Veterinary Public Health & Preventive Health",
  "Veterinary Physiology & Pharmacology",
  "Veterinary Teaching Hospital",
  "Economics",
  "Political Science",
  "Religious Studies",
  "Social Work",
  "Public Administration and Local Government Studies",
  "Geography",
  "Philosophy",
  "Psychology",
  "Sociology and Anthropology",
  "Medical Laboratory Science",
  "Nursing Science",
  "Medical Rehabilitation",
  "Medical Radiography",
  "Architecture",
  "Estate Management",
  "Urban and Regional Planning",
  "Geoinformatics and Surveying",
  "Banking and Finance",
  "Marketing",
  "Business Management",
  "Accountancy",
  "Commercial and Corporate Law",
  "Customary and Indigenous Law",
  "International and Comparative Law",
  "Jurisprudence and Legal Theory",
  "Private Law",
  "Property Law",
  "Public Law",
  "Human Anatomy",
  "Medical Biochemistry",
  "Human Physiology",
  "Anaesthesia",
  "Chemical Pathology",
  "Community Medicine",
  "Haematology and Immunology",
  "Medical Biochemistry",
  "Medical Microbiology",
  "Medicine",
  "Morbid Anatomy",
  "Obstetrics & Gynaecology",
  "Ophthalmology",
  "Otolaryngology",
  "Paediatrics",
  "Pharmacology & Therapeutics",
  "Psychological Medicine",
  "Radiation Medicine",
  "Surgery",
  "Sub-Department of Paediatric Surgery",
  "DentistryChild Dental Health",
  "Oral and Maxillo-Facial Surgery",
  "Preventive Dentistry",
  "Restorative Dentistry"
];
